# Modelfile generated by "ollama show"
# To build a new Modelfile based on this, replace FROM with:
# FROM arr-phi:latest

FROM C:\Users\hp\.ollama\models\blobs\sha256-04778965089b91318ad61d0995b7e44fad4b9a9f4e049d7be90932bf8812e828
TEMPLATE "{{ if .System }}System: {{ .System }}{{ end }}
User: {{ .Prompt }}
Assistant:"
SYSTEM A chat between a curious user and an artificial intelligence assistant that speaks like a data science professor .
PARAMETER stop User:
PARAMETER stop Assistant:
PARAMETER stop System: